package ng.wimika.moneyguardsdkclient.ui.features.startriskchecks

object RiskConstants {
    const val SPECIFIC_RISK_DEVICE_SECURITY_MISCONFIGURATION_USB_DEBUGGING_NAME = "USB_DEBUGGING_ENABLED"
    const val SPECIFIC_RISK_NETWORK_WIFI_ENCRYPTION_NAME = "UNSECURED_WIFI_ENCRYPTION"
    const val SPECIFIC_RISK_NETWORK_WIFI_PASSWORD_PROTECTION_NAME = "UNSECURED_WIFI_PASSWORD"
    const val SPECIFIC_RISK_DEVICE_ROOT_OR_JAILBREAK_NAME = "DEVICE_ROOTED_OR_JAILBROKEN"
    const val SPECIFIC_RISK_NETWORK_DNS_SPOOFING_NAME = "DNS_SPOOFING_DETECTED"
    const val SPECIFIC_RISK_DEVICE_SECURITY_MISCONFIGURATION_LOW_QUALITY_DEVICE_PASSWORD_NAME = "LOW_QUALITY_DEVICE_PASSWORD"
} 